param(
    [Parameter(Mandatory = $true)]
    [string]$Id,

    [string]$Name = "",

    [Parameter(Mandatory = $true)]
    [string]$Image,

    [string]$Type = "resource",

    [bool]$Stackable = $false,

    [double]$Value = 1,

    [string[]]$Actions = @(),

    [int]$CellSize = 6,

    [int]$PaletteColors = 24,

    [int]$Upscale = 6,

    [int]$Size = 32,

    [int]$Depth = 4,

    [double]$Threshold = 35,

    [double]$Scale = 0.05
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if ($Id -notmatch '^[a-z0-9_]+$') {
    throw "Id must match ^[a-z0-9_]+$"
}

if ($Name -eq "") {
    $parts = ($Id -split "_") | Where-Object { $_ -ne "" } | ForEach-Object { $_.Substring(0, 1).ToUpper() + $_.Substring(1) }
    $Name = [string]::Join(" ", $parts)
}

if ($Value -lt 0) {
    throw "Value must be >= 0"
}

$resolvedActions = @()
if ($Actions -and $Actions.Count -gt 0) {
    foreach ($action in $Actions) {
        if ([string]::IsNullOrWhiteSpace($action)) { continue }
        $resolvedActions += $action.Trim()
    }
}

if ($resolvedActions.Count -eq 0) {
    if ($Type -eq "weapon") { $resolvedActions += "Equip" }
    if ($Type -eq "food") { $resolvedActions += "Eat" }
    $resolvedActions += "Use"
    $resolvedActions += "Drop"
}

$resolvedActions = @($resolvedActions | Group-Object { $_.ToLowerInvariant() } | ForEach-Object { $_.Group[0] })

$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..\..")).Path
$imageFull = (Resolve-Path -Path $Image -ErrorAction Stop).Path

$inputDir = Join-Path $projectRoot "assets\input"
$pixelDir = Join-Path $projectRoot "assets\pixel"
$modelDir = Join-Path $projectRoot "assets\models"
$itemsDir = Join-Path $projectRoot "content\items"

New-Item -ItemType Directory -Force -Path $inputDir, $pixelDir, $modelDir, $itemsDir | Out-Null

$sourceExt = [System.IO.Path]::GetExtension($imageFull)
if ([string]::IsNullOrWhiteSpace($sourceExt)) {
    $sourceExt = ".png"
}

$sourceCopy = Join-Path $inputDir "$Id-source$sourceExt"
Copy-Item -Path $imageFull -Destination $sourceCopy -Force

$iconPath = Join-Path $pixelDir "$Id-pixel.png"
$modelPath = Join-Path $modelDir "$Id.obj"
$groundModelPath = Join-Path $modelDir "$Id-ground.obj"
$itemPath = Join-Path $itemsDir "$Id.json"

$pixelizeScript = Join-Path $projectRoot "tools\pixel\pixelize.ps1"
& powershell -ExecutionPolicy Bypass -File $pixelizeScript -InputPath $sourceCopy -OutputPath $iconPath -CellSize $CellSize -PaletteColors $PaletteColors -Upscale $Upscale
if ($LASTEXITCODE -ne 0) {
    throw "Pixelize step failed"
}

$modelScript = Join-Path $projectRoot "tools\model\image-to-obj.ps1"
& powershell -ExecutionPolicy Bypass -File $modelScript -InputPath $iconPath -OutputPath $modelPath -Size $Size -Depth $Depth -Threshold $Threshold -Scale $Scale -Mode auto
if ($LASTEXITCODE -ne 0) {
    throw "Model generation step failed"
}

Copy-Item -Path $modelPath -Destination $groundModelPath -Force

$itemData = [ordered]@{
    id = $Id
    name = $Name
    type = $Type
    stackable = $Stackable
    value = $Value
    actions = $resolvedActions
    equipSlot = $null
    assets = [ordered]@{
        icon = "assets/pixel/$Id-pixel.png"
        model = "assets/models/$Id.obj"
        groundModel = "assets/models/$Id-ground.obj"
    }
    notes = "Auto-generated by tool:item:create"
}

$itemData | ConvertTo-Json -Depth 8 | Set-Content -Path $itemPath

Write-Host "Created/updated item: $itemPath"
Write-Host "- Source copy: $sourceCopy"
Write-Host "- Icon: $iconPath"
Write-Host "- Model: $modelPath"
Write-Host "- Ground model: $groundModelPath"
