const { validatePixelSource, getSolidPixelCoords } = require("./pixel-source");

function buildObjFromPixelSource(source) {
  const validation = validatePixelSource(source);
  if (validation.errors.length > 0) {
    throw new Error(validation.errors.join("; "));
  }

  const normalized = validation.normalized;
  const width = normalized.width;
  const height = normalized.height;
  const depth = normalized.model.depth;
  const scale = normalized.model.scale;
  const solidPixels = getSolidPixelCoords(normalized);

  if (solidPixels.length === 0) {
    throw new Error(`pixel asset '${normalized.id}' has no solid pixels`);
  }

  const voxels = new Set();
  for (let i = 0; i < solidPixels.length; i += 1) {
    const pixel = solidPixels[i];
    for (let z = 0; z < depth; z += 1) {
      voxels.add(`${pixel[0]},${pixel[1]},${z}`);
    }
  }

  const vertexMap = new Map();
  const vertexLines = [];
  const faceLines = [];

  function addVertex(x, y, z) {
    const key = `${x.toFixed(6)},${y.toFixed(6)},${z.toFixed(6)}`;
    if (vertexMap.has(key)) return vertexMap.get(key);
    const index = vertexMap.size + 1;
    vertexMap.set(key, index);
    vertexLines.push(`v ${x.toFixed(6)} ${y.toFixed(6)} ${z.toFixed(6)}`);
    return index;
  }

  function addFace(a, b, c, d) {
    const ia = addVertex(a[0], a[1], a[2]);
    const ib = addVertex(b[0], b[1], b[2]);
    const ic = addVertex(c[0], c[1], c[2]);
    const id = addVertex(d[0], d[1], d[2]);
    faceLines.push(`f ${ia} ${ib} ${ic} ${id}`);
  }

  function hasVoxel(x, y, z) {
    return voxels.has(`${x},${y},${z}`);
  }

  const offsetX = -width / 2;
  const offsetZ = -depth / 2;

  voxels.forEach((key) => {
    const parts = key.split(",");
    const x = Number(parts[0]);
    const y = Number(parts[1]);
    const z = Number(parts[2]);

    const x0 = (x + offsetX) * scale;
    const x1 = (x + 1 + offsetX) * scale;
    const yFromBottom = height - 1 - y;
    const y0 = yFromBottom * scale;
    const y1 = (yFromBottom + 1) * scale;
    const z0 = (z + offsetZ) * scale;
    const z1 = (z + 1 + offsetZ) * scale;

    if (!hasVoxel(x + 1, y, z)) addFace([x1, y0, z0], [x1, y1, z0], [x1, y1, z1], [x1, y0, z1]);
    if (!hasVoxel(x - 1, y, z)) addFace([x0, y0, z1], [x0, y1, z1], [x0, y1, z0], [x0, y0, z0]);
    if (!hasVoxel(x, y + 1, z)) addFace([x0, y1, z1], [x1, y1, z1], [x1, y1, z0], [x0, y1, z0]);
    if (!hasVoxel(x, y - 1, z)) addFace([x1, y0, z1], [x0, y0, z1], [x0, y0, z0], [x1, y0, z0]);
    if (!hasVoxel(x, y, z + 1)) addFace([x0, y0, z1], [x1, y0, z1], [x1, y1, z1], [x0, y1, z1]);
    if (!hasVoxel(x, y, z - 1)) addFace([x1, y0, z0], [x0, y0, z0], [x0, y1, z0], [x1, y1, z0]);
  });

  const lines = [
    "# Generated by tools/pixel/pixel-model.js",
    `o ${normalized.id}`
  ].concat(vertexLines, faceLines);

  return {
    text: lines.join("\n") + "\n",
    stats: {
      solidPixels: solidPixels.length,
      depth,
      scale,
      vertices: vertexLines.length,
      faces: faceLines.length
    }
  };
}

module.exports = {
  buildObjFromPixelSource
};
